spring:
  application:
    name: ms-accounts
  webflux:
    base-path: /
  data:
    mongodb:
      uri: mongodb://admin:{cipher}9bf3484c0b31bc544e04a5c128a39928141fe819109a0847857a8468e48491e34da39348011433a10abe9c215cb5971a@mongodb-prod:27017/accounts_db_prod?authSource=admin

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-eureka:8761/eureka/}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

services:
  customer:
    url: ${SERVICE_CUSTOMER_URL:http://ms-customer:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,circuitbreakermetrics
  endpoint:
    health:
      show-details: always
