spring:
  application:
    name: ms-accounts
  webflux:
    base-path: /
  data:
    mongodb:
      host: mongodb-accounts
      port: 27017
      database: ms_accounts_prod
      authentication-database: admin
      username: admin
      password: '{cipher}e4cfe64713f2ff33acb683523b3149921690dbe7d4ba9cf261c83b5578cbc63dbe9e9c62f8f440638a7cd8ba8e8591c3'
      auto-index-creation: true
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://service-eureka:8761/eureka/}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

services:
  customer:
    url: ${SERVICE_CUSTOMER_URL:http://ms-customer:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,circuitbreakermetrics
  endpoint:
    health:
      show-details: always
