spring:
  application:
    name: ms-transaction
  data:
    mongodb:
      uri: mongodb://admin:{cipher}4f9c17ada64b584ecbb564ffca2f15afb82dae15fd2aac9d8ac6aa38bcd320fe5e2070d6e921acd378cfd1d1169a7be1@mongodb-prod:27017/bootcamp_prod?authSource=admin
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-prod:9092}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
    properties:
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME:admin}" password="{cipher}4f9c17ada64b584ecbb564ffca2f15afb82dae15fd2aac9d8ac6aa38bcd320fe5e2070d6e921acd378cfd1d1169a7be1";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-prod:9092}
      group-id: ms-transaction-group-prod
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      account-validation:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
  timelimiter:
    instances:
      account-validation:
        cancelRunningFuture: true
        timeoutDuration: 2s
  retry:
    instances:
      account-validation:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-eureka:8761/eureka/}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
