spring:
  application:
    name: ms-credits
  data:
    mongodb:
      uri: mongodb://admin:{cipher}86d968374834af94a02569507e970b33aa61974f692a24c3297ccbda05274fd7569dbef63016812c73959988822427e1@mongodb-prod:27017/ms_credits_prod?authSource=admin
      auto-index-creation: true
  webflux:
    base-path: /api
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-eureka:8761/eureka/}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,circuitbreaker-events
  endpoint:
    health:
      show-details: always
