spring:
  application:
    name: ms-credits
  data:
    mongodb:
      host: mongodb-credits
      port: 27017
      database: ms_credits_prod
      authentication-database: admin
      username: admin
      password: '{cipher}97fc950e3f921c098f85893eff72caf15feb00d66bd360d4465d96aa45b17561300641769c288016e9ff5eaca46bac1e'
      auto-index-creation: true
  webflux:
    base-path: /

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://service-eureka:8761/eureka/}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        health,info,metrics,prometheus,circuitbreakers,circuitbreaker-events,retries,retry-events,rate-limiters,rate-limiter-events,time-limiters,time-limiter-events
  endpoint:
    health:
      show-details: always
