spring:
  application:
    name: ms-credits
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms_credits_dev
  webflux:
    base-path: /
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: 8083

logging:
  level:
    com.bootcamp: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,circuitbreaker-events
  endpoint:
    health:
      show-details: always
