spring:
  application:
    name: ms-credits
  data:
    mongodb:
      host: mongodb-accounts
      port: 27017
      database: ms_accounts_prod
      authentication-database: admin
      username: admin
      password: '{cipher}cdcef99b8702eb4995cc57c8c676ef312c5350afa0781800ea2820f5d8436797d40c219dc9e7410458bab0dc3cac1d18'
      auto-index-creation: true
  webflux:
    base-path: /

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://service-eureka:8761/eureka/}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        health,info,metrics,prometheus,circuitbreakers,circuitbreaker-events,retries,retry-events,rate-limiters,rate-limiter-events,time-limiters,time-limiter-events
  endpoint:
    health:
      show-details: always
